flatpak install --system app.drey.Dialect -y
flatpak install --system com.belmoussaoui.Obfuscate -y
flatpak install --system com.boxy_svg.BoxySVG -y
flatpak install --system com.github.tchx84.Flatseal -y
flatpak install --system com.heroicgameslauncher.hgl -y
flatpak install --system com.jetbrains.IntelliJ-IDEA-Community -y
flatpak install --system com.mattjakeman.ExtensionManager -y
flatpak install --system com.rtosta.zapzap -y
flatpak install --system com.spotify.Client -y
flatpak install --system io.github.giantpinkrobots.varia -y
flatpak install --system io.github.shiftey.Desktop -y
flatpak install --system io.github.vikdevelop.SaveDesktop -y
flatpak install --system net.nokyan.Resources -y
flatpak install --system org.gaphor.Gaphor -y
flatpak install --system org.gnome.Evolution -y
flatpak install --system org.gnome.gitlab.somas.Apostrophe -y
flatpak install --system org.onlyoffice.desktopeditors -y
flatpak install --system org.texstudio.TeXstudio -y
flatpak install --system org.videolan.VLC -y
flatpak install --system org.virt_manager.virt-manager -y
flatpak install --system page.tesk.Refine -y
